name: DevOps

on:
  [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test

    strategy:
      matrix:
        php-version: [ 8.3, 8.4 ]

    steps:
    - name: Git checkout
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@master
      with:
        php-version: ${{ matrix.php-version }}

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install PHP dependencies
      run: composer install --prefer-dist --no-progress --no-suggest --no-scripts

    - name: Run test suite
      run: composer run-script test
